name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - scikit-learn
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - scikit-image
